# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Ales Tsurko Software Support

# Short description (goes below the title; it will also be used in the RSS feed)
description: 

# Your name, as you want it to appear underneath each post and in the footer
author: 

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /support

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://alestsurko.by/support

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: alestsurko-support

# The public key for your disqus application
disqus_publickey: DwgfmL74LKb6SrpcVzymdOFtKRoDzwAXVtb4QKTLbi14LGks4FlHLKut5gcC8a9P
